#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
BASEPATH=$( cd $SCRIPTPATH/../; pwd -P )

export SCRIPTPATH
export BASEPATH

YEARMONTH=$(date +%Y%m)

logfile=$SCRIPTPATH/$YEARMONTH.log
exec > >( sed -e "s/\r/\n/g" | gawk '{ print strftime("[%Y-%m-%d %H:%M:%S]: "), $0; fflush(); }' >> $logfile ) 2>&1

set -x          # -x print traces
set -eu         # -e If a command fails, stop execution
                # -u Fail if we try to expand unset variables
set -o pipefail # Fail even on pipes

source $BASEPATH/.env
source $SCRIPTPATH/.env

_fail () {
  curl -s $HEALTHCHECK_URL/fail
  exit
}
trap _fail ERR


echo "Init Backup Exec"

curl -s $HEALTHCHECK_URL/start

n=0
until [ "$n" -ge 5 ]
do
   echo "Attempt Backup #$n"
   aws s3 sync /srv s3://$BACKUP_BUCKET/srv --delete && break
   n=$((n+1)) 
   sleep 15
done

curl -s $HEALTHCHECK_URL
